### ISSUE TITLE
composer install issue with php7.4.3 and composer 1.10.1 on Ubuntu 20

### ISSUE THREAD

**Issue by edchelstephens** [kabzko/laravelreactjscrud#2]
Hi, I tried to run your app following the Readme commands.

I'm new to php and laravel, so I just install the php and composer libraries with sudo apt install commands.

I got the following versions:

 php --version
PHP 7.4.3 (cli) (built: Aug 13 2021 05:39:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
    
    
  composer --version
Composer 1.10.1 2020-03-13 20:34:27

When I run `composer install` I get this error:

composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tijsverkoyen/css-to-inline-styles 2.2.3 -> satisfiable by tijsverkoyen/css-to-inline-styles[2.2.3].
    - tijsverkoyen/css-to-inline-styles 2.2.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 2
    - Installation request for phar-io/manifest 2.0.3 -> satisfiable by phar-io/manifest[2.0.3].
    - phar-io/manifest 2.0.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 3
    - Installation request for phpunit/php-code-coverage 9.2.7 -> satisfiable by phpunit/php-code-coverage[9.2.7].
    - phpunit/php-code-coverage 9.2.7 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 4
    - Installation request for phpunit/phpunit 9.5.9 -> satisfiable by phpunit/phpunit[9.5.9].
    - phpunit/phpunit 9.5.9 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 5
    - Installation request for theseer/tokenizer 1.2.1 -> satisfiable by theseer/tokenizer[1.2.1].
    - theseer/tokenizer 1.2.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 6
    - tijsverkoyen/css-to-inline-styles 2.2.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - laravel/framework v8.61.0 requires tijsverkoyen/css-to-inline-styles ^2.2.2 -> satisfiable by tijsverkoyen/css-to-inline-styles[2.2.3].
    - Installation request for laravel/framework v8.61.0 -> satisfiable by laravel/framework[v8.61.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

# How do I fix this?

## Can you upload your app to heroku so we can see a running live demo?

# Thanks!

**Comment by kabzko** [comment]
I'm using latest version of php the v8 and after updating the php version
try entering the command composer install --ignore-platform-reqs

**Comment by edchelstephens** [comment]
I have tried the app.

Thanks!
